### ISSUE TITLE
[UPDATE REQUEST] - Bump to 0.94.0 NuShell!

### ISSUE THREAD

**Issue by pratyushV-l** [JosephTLyons/nu_plugin_units#1]
Would you please consider bumping this to have the dependency of NuShell 0.94.0 as it is currently incompatible. Also consider updating the ReadME file, as it is outdated and is non-applicable for the current version.

**Comment by JosephTLyons** [comment]
Hey @pratyushV-l - have you tried the latest code? I bumped the nushell dependencies, along with the appropriate code changes, last week.

<img width="533" alt="SCR-20240604-upod" src="https://github.com/JosephTLyons/nu_plugin_units/assets/19867440/3c671432-be15-4f62-a00b-865788c6bbe4">

Can you also let me know what part of the README.md you think is outdated? I've added instructions for how to install it, as that might've changed on Nushell's end.

**Comment by JosephTLyons** [comment]
I'm going to close this issue, as I think things are working correctly, but please let me know if you're having any issues and I'll try to help you as best as I can.
