### ISSUE TITLE
error in nushell 0.97.2

### ISSUE THREAD

**Issue by kurokirasama** [JosephTLyons/nu_plugin_units#2]
Hey, I just updated nushell to 0.97.2, but when doing `plugin add ~/.cargo/bin/nu_plugin_port_scan` i get this error:

```
Error: nu::shell::plugin_failed_to_load

  × Plugin failed to load: Plugin `units` is compiled for nushell version 0.94.0, which is not compatible with version 0.97.2
```

**Comment by JosephTLyons** [comment]
Thanks for updating me, it's been a bit hard to keep up with all the breaking changes that occur - hoping one day, things stabilize on their end. I'll fix this this weekend, but for now, you might want to just deregister the plugin so you can use others, if its blocking you.

**Comment by JosephTLyons** [comment]
I've published a new version of `nu_plugin_units` that should run with that latest version of nushell. Let me know if you have any issues!
