### ISSUE TITLE
Not compatible with current version of nu

### ISSUE THREAD

**Issue by Aarkon** [JosephTLyons/nu_plugin_units#3]
I hope it's only me, but when I try `plugin add ... nu_plugin_units`, I get this error:
```
Error:   × Failed to send plugin call to `units`
  help: try loading the plugin again with `plugin use 'units'`

Error: nu::shell::plugin_failed_to_load

  × Plugin failed to load: Plugin `units` is compiled for nushell version 0.97.1, which is not compatible with version 0.99.1
```
It seems to me that some dependency might need to be updated and the plugin released again, but I have never done anything in the realm of plugin development, so don't let me lead you astray if this is implausible.

Love the plugin though, and I dearly want to use it again! :)

**Comment by JosephTLyons** [comment]
Sorry for missing this - I'll hop on fixing this this weekend. I love Nu as well, but there sure are a lot of breaking changes to the protocols! I hope these stabilize one a bit one day. Thanks for bringing this to my attention.

**Comment by JosephTLyons** [comment]
This should now be fixed in `v0.1.3`!

**Comment by Aarkon** [comment]
Verified, it works. Thank you! 👍

**Comment by Aarkon** [comment]
It happened again 🙈

**Comment by JosephTLyons** [comment]
2 polar opposite things:

1. Nushell breaking plugins multiple times a year is killing me.
2. You coming here to report it makes me happy, as I know at least someone is using this thing. Would love to hear about where you are finding this thing useful.

Anyway, I'm on xmas break, so I'll get this, and my other nushell plugins, fixed.

**Comment by JosephTLyons** [comment]
@Aarkon - give `v0.1.4` a shot.

<img width="1608" alt="SCR-20241223-bemd" src="https://github.com/user-attachments/assets/3c075808-84c1-4018-9cba-9557de9d6b94" />

**Comment by Aarkon** [comment]
I'm back from my own x-mas break and now can assess your work.
Right from the bat: It looks great, thank you (again) for the effort! :)

And since you verbalized your interest in my use case: It's rather special I'd say. :sweat_smile: I'm home brewer based in Europe and find myself in need for conversions from imperial units/Fahrenheit to metric/Celsius whenever I dive into international communities around the hobby. As I'm also an avid terminal user, I love the snappiness of having something at hand this quickly without the need to open another browser tab and look for some online conversion tool.  
Also, because I'm lazy a.f., I have written aliases/functions to do the most common conversions without filling in every parameter manually (e.g. Fahrenheit -> Celsius).

Hope that satisfies your curiosity!
